@startuml

entity "User" as user {
  + username: string <<PK>>
  --
  + firstName: string
  + lastName: string
  + phoneNumber: string
  + email: string
  + password: string
  + isLocked: boolean
  + lastUpdated: date
}

entity "Role" as role {
  + roleId: string <<PK>>
  --
  + roleName: string
}

user -right-|{ role : roleId <<FK>>

@enduml