name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  checkout-backend:
    name: Checkout Backend Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  backend-clean:
    name: Clean Backend Environment
    runs-on: ubuntu-latest
    needs: checkout-backend

    steps:
      - name: Clean environment
        run: |
          rm -rf Deliverables/BackendAPI/target/
        working-directory: Deliverables/BackendAPI

  backend-build:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: backend-clean

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install dependencies
        run: mvn dependency:go-offline
        working-directory: Deliverables/BackendAPI

      - name: Build backend
        run: mvn clean package
        working-directory: Deliverables/BackendAPI

  backend-test:
    name: Test Backend and Generate Coverage Report
    runs-on: ubuntu-latest
    needs: backend-build

    steps:
      - name: Run backend tests and generate coverage report
        run: mvn test jacoco:report
        working-directory: Deliverables/BackendAPI

      - name: Archive backend test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: backend-test-coverage
          path: Deliverables/BackendAPI/target/site/jacoco
          if-no-files-found: warn

      - name: Send coverage report to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
          -r Deliverables/BackendAPI/target/site/jacoco/jacoco.xml

  backend-dependency-check:
    name: Analyze Backend Dependencies
    runs-on: ubuntu-latest
    needs: backend-build

    steps:
      - name: Analyze backend dependencies
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.1.6/dependency-check-6.1.6-release.zip
          unzip dependency-check-6.1.6-release.zip
          ./dependency-check/bin/dependency-check.sh --scan target/ --format HTML --out dependency-report/
        working-directory: Deliverables/BackendAPI

      - name: Archive backend dependency report
        uses: actions/upload-artifact@v2
        with:
          name: backend-dependency-report
          path: Deliverables/BackendAPI/dependency-report/
          if-no-files-found: warn

  checkout-frontend:
    name: Checkout Frontend Repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  frontend-clean:
    name: Clean Frontend Environment
    runs-on: ubuntu-latest
    needs: checkout-frontend

    steps:
      - name: Check deliverables folder for frontend
        run: |
          if [ ! -d "Deliverables/EletricGO" ]; then
            echo "Error: 'Deliverables/EletricGO' folder not found for frontend."
            exit 1
          fi

      - name: Clean environment
        run: |
          rm -rf Deliverables/EletricGO/dist/
        working-directory: Deliverables/EletricGO

  frontend-setup:
    name: Setup Frontend Environment
    runs-on: ubuntu-latest
    needs: frontend-clean

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install
        working-directory: Deliverables/EletricGO

  frontend-test:
    name: Test Frontend and Generate Coverage Report
    runs-on: ubuntu-latest
    needs: frontend-setup

    steps:
      - name: Run frontend tests and generate coverage report
        run: npm run test-no-browser
        working-directory: Deliverables/EletricGO

      - name: Archive frontend test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: frontend-test-coverage
          path: Deliverables/EletricGO/coverage
          if-no-files-found: warn

      - name: Send coverage report to Codacy
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
          -r Deliverables/EletricGO/coverage/lcov.info

  frontend-build:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: frontend-setup

    steps:
      - name: Build frontend
        run: npm run prod
        working-directory: Deliverables/EletricGO

      - name: Lint frontend code
        run: npm run lint
        working-directory: Deliverables/EletricGO

  frontend-dependency-check:
    name: Analyze Frontend Dependencies
    runs-on: ubuntu-latest
    needs: frontend-build

    steps:
      - name: Analyze frontend dependencies
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.1.6/dependency-check-6.1.6-release.zip
          unzip dependency-check-6.1.6-release.zip
          ./dependency-check/bin/dependency-check.sh --scan node_modules/ --format HTML --out dependency-report/
        working-directory: Deliverables/EletricGO

      - name: Archive frontend dependency report
        uses: actions/upload-artifact@v2
        with:
          name: frontend-dependency-report
          path: Deliverables/EletricGO/dependency-report/
          if-no-files-found: warn

  deploy-backend-reports:
    name: Deploy Backend Reports
    runs-on: ubuntu-latest
    needs: [backend-test, backend-dependency-check]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download backend dependency report
        uses: actions/download-artifact@v2
        with:
          name: backend-dependency-report
          path: backend-dependency-report/

      - name: Download backend test coverage report
        uses: actions/download-artifact@v2
        with:
          name: backend-test-coverage
          path: backend-test-coverage/

      - name: Deploy Backend Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports/backend

  deploy-frontend-reports:
    name: Deploy Frontend Reports
    runs-on: ubuntu-latest
    needs: [frontend-test, frontend-dependency-check]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download frontend dependency report
        uses: actions/download-artifact@v2
        with:
          name: frontend-dependency-report
          path: frontend-dependency-report/

      - name: Download frontend test coverage report
        uses: actions/download-artifact@v2
        with:
          name: frontend-test-coverage
          path: frontend-test-coverage/

      - name: Deploy Frontend Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports/frontend
