name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check deliverables folder for frontend
        run: |
          if [ ! -d "Deliverables" ]; then
            echo "Error: 'Deliverables' folder not found for frontend."
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: ng build --prod

      - name: Run ESLint checks
        run: npm run lint

  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check deliverables folder for backend
        run: |
          if [ ! -d "Deliverables/BackendAPI" ]; then
            echo "Error: 'Deliverables/BackendAPI' folder not found for backend."
            exit 1
          fi

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      # Add other steps for backend build here
      # Example:
      # - name: Build with Maven
      #   run: mvn clean install -DskipTests

      - name: Run Spring Boot tests
        run: |
          cd Deliverables/BackendAPI
          mvn test

  # Optionally add a deployment job if needed
