name: CI
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
 
jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Clean environment
        run: |
          rm -rf Deliverables/BackendAPI/target/
        working-directory: Deliverables/BackendAPI
 
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
 
      - name: Install dependencies
        run: mvn dependency:go-offline
        working-directory: Deliverables/BackendAPI
 
      - name: Build backend
        run: mvn clean package
        working-directory: Deliverables/BackendAPI
 
      - name: Run backend tests
        run: mvn test
        working-directory: Deliverables/BackendAPI
 
      - name: Analyze backend dependencies
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.1.6/dependency-check-6.1.6-release.zip
          unzip dependency-check-6.1.6-release.zip
          ./dependency-check/bin/dependency-check.sh --scan target/ --format HTML --out dependency-report/
        working-directory: Deliverables/BackendAPI
 
      - name: Archive backend artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifact
          path: target/*.jar
 
      - name: Archive backend dependency report
        uses: actions/upload-artifact@v2
        with:
          name: backend-dependency-report
          path: dependency-report/
 
  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Check deliverables folder for frontend
        run: |
          if [ ! -d "Deliverables/EletricGo" ]; then
            echo "Error: 'Deliverables/EletricGo' folder not found for frontend."
            exit 1
          fi
 
      - name: Clean environment
        run: |
          rm -rf Deliverables/EletricGo/dist/
        working-directory: Deliverables/EletricGo
 
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
 
      - name: Install Angular CLI
        run: npm install -g @angular/cli
 
      - name: Install dependencies
        run: npm install
        working-directory: Deliverables/EletricGo
 
      - name: Build frontend
        run: npm run build -- --prod
        working-directory: Deliverables/EletricGo
 
      - name: Lint frontend code
        run: npm run lint
        working-directory: Deliverables/EletricGo
 
      - name: Analyze frontend dependencies
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.1.6/dependency-check-6.1.6-release.zip
          unzip dependency-check-6.1.6-release.zip
          ./dependency-check/bin/dependency-check.sh --scan node_modules/ --format HTML --out dependency-report/
        working-directory: Deliverables/EletricGo
 
      - name: Archive frontend artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-artifact
          path: dist/
 
      - name: Archive frontend dependency report
        uses: actions/upload-artifact@v2
        with:
          name: frontend-dependency-report
          path: dependency-report/
